//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FirmaEntities : DbContext
    {
        public FirmaEntities()
            : base("name=FirmaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Kontakty> Kontakties { get; set; }
        public virtual DbSet<Manager> Managers { get; set; }
        public virtual DbSet<Oddzial> Oddzials { get; set; }
        public virtual DbSet<Pracownicy> Pracownicies { get; set; }
    }
}
