//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp2
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class Pracownicy
    {
        public int IDP { get; set; }
        public string Imie { get; set; }
        public string Nazwisko { get; set; }
        public int Szef { get; set; }
        public int Dane_Kontaktowe { get; set; }
        public int Dzial { get; set; }
    
        public virtual Kontakty Kontakty { get; set; }
        public virtual Manager Manager { get; set; }
        public virtual Oddzial Oddzial { get; set; }
    }
}
